server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/productdb}
    username: ${SPRING_DATASOURCE_USERNAME:product}
    password: ${SPRING_DATASOURCE_PASSWORD:product123}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCE_SERVER_JWT_URI:http://localhost:8080/realms/ecom}
